import { drizzle } from 'drizzle-orm/node-postgres';
import { Pool } from 'pg';
import { place } from './schema/places';

import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

dotenv.config({
  path: path.resolve(__dirname, '../../../apps/web/.env'),
});

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const db = drizzle(pool);

// ---------------------------------------------------------------------------
// Seed data — all places from the static database.ts with real coordinates
// and Indian ticket prices in paise (₹ × 100)
// ---------------------------------------------------------------------------

const places: (typeof place.$inferInsert)[] = [
  // ─── 10 MONUMENTS ─────────────────────────────────────────────────────────
  {
    name: 'Amber Fort',
    slug: 'amber-fort',
    type: 'monument',
    country: 'India',
    state: 'Rajasthan',
    city: 'Jaipur',
    location: 'Devisinghpura, Amer, Jaipur, Rajasthan 302028',
    latitude: 26.9855,
    longitude: 75.8513,
    googleMapLink: 'https://goo.gl/maps/jn8W6QqDnkq',
    images: ['', '', '', '', ''],
    videos: [''],
    shortDesc: 'A majestic hilltop fort known for its artistic Hindu-style elements and Sheesh Mahal.',
    longDesc: 'Built by Raja Man Singh I in 1592, Amber Fort is a UNESCO World Heritage site. It is famous for its large ramparts, series of gates, and cobbled paths. The Maota Lake provides a stunning reflection of the fort.',
    precautionAndSafety: ['Wear comfortable shoes for uphill walking.', 'Carry water.', 'Watch out for monkeys.'],
    metadata: [
      { label: 'Best Time', data: 'October to March' },
      { label: 'Open Time', data: '8:00 AM' },
      { label: 'Close Time', data: '5:30 PM' },
      { label: 'Entry Fees', data: '₹100 (Indians), ₹500 (Foreigners)' },
    ],
    ticketPrice: 10000,
    isActive: true,
  },
  {
    name: 'Hawa Mahal',
    slug: 'hawa-mahal',
    type: 'monument',
    country: 'India',
    state: 'Rajasthan',
    city: 'Jaipur',
    location: 'Hawa Mahal Rd, Badi Choupad, J.D.A. Market, Jaipur, Rajasthan 302002',
    latitude: 26.9239,
    longitude: 75.8267,
    googleMapLink: 'https://goo.gl/maps/yTfn5UemYxT2',
    images: ['', '', '', '', ''],
    videos: [''],
    shortDesc: 'The "Palace of Breeze" with 953 honeycombed windows.',
    longDesc: 'Constructed in 1799 by Maharaja Sawai Pratap Singh, its unique five-story exterior is akin to the honeycomb of a beehive. It allowed royal women to observe street festivals without being seen.',
    precautionAndSafety: ['Stairs are steep and narrow.', 'Stay hydrated.'],
    metadata: [
      { label: 'Open Time', data: '9:00 AM' },
      { label: 'Close Time', data: '5:00 PM' },
      { label: 'Entry Fees', data: '₹50 (Indians), ₹200 (Foreigners)' },
    ],
    ticketPrice: 5000,
    isActive: true,
  },
  {
    name: 'Jantar Mantar',
    slug: 'jantar-mantar',
    type: 'monument',
    country: 'India',
    state: 'Rajasthan',
    city: 'Jaipur',
    location: 'Gangori Bazaar, J.D.A. Market, Jaipur, Rajasthan 302002',
    latitude: 26.9247,
    longitude: 75.8242,
    googleMapLink: 'https://goo.gl/maps/ZnJZBmZqGxn',
    images: ['', '', '', '', ''],
    videos: [''],
    shortDesc: 'A collection of nineteen architectural astronomical instruments.',
    longDesc: 'A UNESCO World Heritage site featuring the world\'s largest stone sundial. It was built by Rajput King Sawai Jai Singh II to measure time and track celestial bodies.',
    precautionAndSafety: ['Hire a guide to understand the instruments.', 'Avoid touching the structures.'],
    metadata: [
      { label: 'Open Time', data: '9:00 AM' },
      { label: 'Close Time', data: '4:30 PM' },
      { label: 'Entry Fees', data: '₹50 (Indians), ₹200 (Foreigners)' },
    ],
    ticketPrice: 5000,
    isActive: true,
  },
  {
    name: 'Chittorgarh Fort',
    slug: 'chittorgarh-fort',
    type: 'monument',
    country: 'India',
    state: 'Rajasthan',
    city: 'Chittorgarh',
    location: 'Chittorgarh, Rajasthan 312001',
    latitude: 24.8879,
    longitude: 74.6451,
    googleMapLink: 'https://goo.gl/maps/chittor-link',
    images: ['', '', '', '', ''],
    videos: [''],
    shortDesc: 'The largest fort in India and the grandest in Rajasthan.',
    longDesc: 'Spanning 700 acres, this UNESCO site is a symbol of Rajput bravery. Key highlights include the Vijay Stambha (Tower of Victory) and the Padmini Palace.',
    precautionAndSafety: ['The fort is massive; use a vehicle to move between points.', 'Hire a licensed guide.'],
    metadata: [
      { label: 'Open Time', data: '9:30 AM' },
      { label: 'Close Time', data: '6:30 PM' },
      { label: 'Entry Fees', data: '₹50 (Indians), ₹200 (Foreigners)' },
    ],
    ticketPrice: 5000,
    isActive: true,
  },
  {
    name: 'Mehrangarh Fort',
    slug: 'mehrangarh-fort',
    type: 'monument',
    country: 'India',
    state: 'Rajasthan',
    city: 'Jodhpur',
    location: 'P.B. No 165, The Fort, Jodhpur, Rajasthan 342006',
    latitude: 26.2980,
    longitude: 73.0188,
    googleMapLink: 'https://goo.gl/maps/TDPYvzkkt9x',
    images: ['', '', '', '', ''],
    videos: [''],
    shortDesc: 'A formidable fort rising 410 feet above the "Blue City".',
    longDesc: 'Founded by Rao Jodha in 1459, it features thick walls and several palaces known for their intricate carvings and expansive courtyards.',
    precautionAndSafety: ['Use the elevator to reach the top if needed.', 'Wear sun hats.'],
    metadata: [
      { label: 'Open Time', data: '9:00 AM' },
      { label: 'Close Time', data: '5:30 PM' },
      { label: 'Entry Fees', data: '₹200 (Indians), ₹600 (Foreigners)' },
    ],
    ticketPrice: 20000,
    isActive: true,
  },
  {
    name: 'Kumbhalgarh Fort',
    slug: 'kumbhalgarh-fort',
    type: 'monument',
    country: 'India',
    state: 'Rajasthan',
    city: 'Rajsamand',
    location: 'Kumbhalgarh, Rajasthan 313325',
    latitude: 25.1485,
    longitude: 73.5875,
    googleMapLink: 'https://goo.gl/maps/kumbhalgarh-link',
    images: ['', '', '', '', ''],
    videos: [''],
    shortDesc: 'Known for its 36km long wall, the second longest in the world.',
    longDesc: 'Built by Rana Kumbha, it is the birthplace of Maharana Pratap. Its wall is thick enough for eight horses to ride abreast.',
    precautionAndSafety: ['Steep incline while walking to Badal Mahal.', 'Carry drinking water.'],
    metadata: [
      { label: 'Open Time', data: '9:00 AM' },
      { label: 'Close Time', data: '6:00 PM' },
      { label: 'Entry Fees', data: '₹40 (Indians), ₹600 (Foreigners)' },
    ],
    ticketPrice: 4000,
    isActive: true,
  },
  {
    name: 'Jaisalmer Fort',
    slug: 'jaisalmer-fort',
    type: 'monument',
    country: 'India',
    state: 'Rajasthan',
    city: 'Jaisalmer',
    location: 'Fort Road, Jaisalmer, Rajasthan 345001',
    latitude: 26.9137,
    longitude: 70.9165,
    googleMapLink: 'https://goo.gl/maps/L5Kq1DB3G4D2',
    images: ['', '', '', '', ''],
    videos: [''],
    shortDesc: 'A "Living Fort" made of golden sandstone.',
    longDesc: 'Built in 1156, it is one of the few forts in the world where people still live and run shops within the ramparts.',
    precautionAndSafety: ['Respect the residents\' privacy.', 'Avoid peak noon hours.'],
    metadata: [
      { label: 'Open Time', data: '9:00 AM' },
      { label: 'Close Time', data: '6:00 PM' },
      { label: 'Entry Fees', data: '₹50 (Indians), ₹250 (Foreigners)' },
    ],
    ticketPrice: 5000,
    isActive: true,
  },
  {
    name: 'Jaigarh Fort',
    slug: 'jaigarh-fort',
    type: 'monument',
    country: 'India',
    state: 'Rajasthan',
    city: 'Jaipur',
    location: 'Above Amer Fort, Jaipur, Rajasthan 302001',
    latitude: 26.9908,
    longitude: 75.8475,
    googleMapLink: 'https://goo.gl/maps/jaigarh-link',
    images: ['', '', '', '', ''],
    videos: [''],
    shortDesc: 'Home to the Jaivana, the world\'s largest cannon on wheels.',
    longDesc: 'Built to protect the Amber Fort complex, it offers panoramic views of the Aravalli hills and Maota Lake.',
    precautionAndSafety: ['Large area; be prepared for significant walking.'],
    metadata: [
      { label: 'Open Time', data: '9:00 AM' },
      { label: 'Close Time', data: '4:30 PM' },
      { label: 'Entry Fees', data: '₹100 (Indians), ₹200 (Foreigners)' },
    ],
    ticketPrice: 10000,
    isActive: true,
  },
  {
    name: 'Junagarh Fort',
    slug: 'junagarh-fort',
    type: 'monument',
    country: 'India',
    state: 'Rajasthan',
    city: 'Bikaner',
    location: 'Junagarh Fort Rd, Bikaner, Rajasthan 334001',
    latitude: 28.0229,
    longitude: 73.3119,
    googleMapLink: 'https://goo.gl/maps/qMhwHMWN3Fq',
    images: ['', '', '', '', ''],
    videos: [''],
    shortDesc: 'A rare fort not built on a hill, featuring mixed architectural styles.',
    longDesc: 'Originally called Chintamani, it was built by Raja Rai Singh in 1589 and was never conquered throughout its history.',
    precautionAndSafety: ['Guides are available in multiple languages.'],
    metadata: [
      { label: 'Open Time', data: '10:00 AM' },
      { label: 'Close Time', data: '4:30 PM' },
      { label: 'Entry Fees', data: '₹50 (Indians), ₹300 (Foreigners)' },
    ],
    ticketPrice: 5000,
    isActive: true,
  },
  {
    name: 'Vijay Stambha',
    slug: 'vijay-stambha',
    type: 'monument',
    country: 'India',
    state: 'Rajasthan',
    city: 'Chittorgarh',
    location: 'Inside Chittorgarh Fort, Chittorgarh, Rajasthan 312001',
    latitude: 24.8879,
    longitude: 74.6451,
    googleMapLink: 'https://goo.gl/maps/vijay-stambha',
    images: ['', '', '', '', ''],
    videos: [''],
    shortDesc: 'A massive victory tower commemorating Rana Kumbha\'s win.',
    longDesc: 'Standing nine stories high, this 15th-century tower is dedicated to Lord Vishnu and is covered in intricate carvings of Hindu deities.',
    precautionAndSafety: ['The internal staircase is very narrow and dark.'],
    metadata: [
      { label: 'Open Time', data: '9:30 AM' },
      { label: 'Close Time', data: '5:00 PM' },
      { label: 'Note', data: 'Entry included in Fort ticket.' },
    ],
    ticketPrice: 0,
    isActive: true,
  },

  // ─── 10 MUSEUMS ──────────────────────────────────────────────────────────
  {
    name: 'Albert Hall Museum',
    slug: 'albert-hall-museum',
    type: 'museum',
    country: 'India',
    state: 'Rajasthan',
    city: 'Jaipur',
    location: 'Ram Niwas Garden, Ashok Nagar, Jaipur, Rajasthan 302001',
    latitude: 26.9124,
    longitude: 75.8178,
    googleMapLink: 'https://goo.gl/maps/1dRM3dM5aV32',
    images: ['', '', '', '', ''],
    videos: [''],
    shortDesc: 'Rajasthan\'s oldest museum featuring an Egyptian mummy.',
    longDesc: 'An Indo-Saracenic architectural masterpiece housing a rich collection of artifacts, pottery, and carpets.',
    precautionAndSafety: ['Photography requires a separate ticket.', 'Flash is prohibited.'],
    metadata: [
      { label: 'Open Time', data: '9:00 AM' },
      { label: 'Close Time', data: '5:00 PM' },
      { label: 'Entry Fees', data: '₹40 (Indians), ₹300 (Foreigners)' },
    ],
    ticketPrice: 4000,
    isActive: true,
  },
  {
    name: 'City Palace Museum Jaipur',
    slug: 'city-palace-museum-jaipur',
    type: 'museum',
    country: 'India',
    state: 'Rajasthan',
    city: 'Jaipur',
    location: 'Tulsi Marg, Gangori Bazaar, Jaipur, Rajasthan 302002',
    latitude: 26.9258,
    longitude: 75.8237,
    googleMapLink: 'https://goo.gl/maps/city-palace-jaipur',
    images: ['', '', '', '', ''],
    videos: [''],
    shortDesc: 'Showcases royal textiles, weapons, and paintings.',
    longDesc: 'Known officially as the Maharaja Sawai Man Singh II Museum, it houses two world-record-sized silver urns.',
    precautionAndSafety: ['Some areas restricted (private residence).', 'Online booking recommended.'],
    metadata: [
      { label: 'Open Time', data: '9:30 AM' },
      { label: 'Close Time', data: '5:00 PM' },
      { label: 'Entry Fees', data: '₹200 (Indians), ₹700 (Foreigners)' },
    ],
    ticketPrice: 20000,
    isActive: true,
  },
  {
    name: 'Sardar Government Museum',
    slug: 'sardar-government-museum',
    type: 'museum',
    country: 'India',
    state: 'Rajasthan',
    city: 'Jodhpur',
    location: 'Umaid Bagh, Jodhpur, Rajasthan 342001',
    latitude: 26.2912,
    longitude: 73.0332,
    googleMapLink: 'https://goo.gl/maps/sardar-museum',
    images: ['', '', '', '', ''],
    videos: [''],
    shortDesc: 'A British-era museum inside Umaid Public Gardens.',
    longDesc: 'Built in 1909, it displays portraits of kings, stone sculptures, and terracotta from ancient sites.',
    precautionAndSafety: ['Usually closed on Fridays and public holidays.'],
    metadata: [
      { label: 'Open Time', data: '10:00 AM' },
      { label: 'Close Time', data: '5:00 PM' },
      { label: 'Entry Fees', data: '₹20 (Indians), ₹100 (Foreigners)' },
    ],
    ticketPrice: 2000,
    isActive: true,
  },
  {
    name: 'Ahar Archaeological Museum',
    slug: 'ahar-museum-udaipur',
    type: 'museum',
    country: 'India',
    state: 'Rajasthan',
    city: 'Udaipur',
    location: 'Ahar, Udaipur, Rajasthan 313001',
    latitude: 24.5902,
    longitude: 73.7145,
    googleMapLink: 'https://goo.gl/maps/ahar-link',
    images: ['', '', '', '', ''],
    videos: [''],
    shortDesc: 'Exhibits items from the 4,000-year-old Ahar culture.',
    longDesc: 'Houses a rare collection of earthen pots, iron objects, and sculptures dating back to the 10th century.',
    precautionAndSafety: ['Wear shoes suitable for walking in the adjacent cenotaphs.'],
    metadata: [
      { label: 'Open Time', data: '10:00 AM' },
      { label: 'Close Time', data: '4:30 PM' },
      { label: 'Entry Fees', data: '₹3 (Indians), ₹10 (Foreigners)' },
    ],
    ticketPrice: 300,
    isActive: true,
  },
  {
    name: 'Jaisalmer War Museum',
    slug: 'jaisalmer-war-museum',
    type: 'museum',
    country: 'India',
    state: 'Rajasthan',
    city: 'Jaisalmer',
    location: 'Jaisalmer-Jodhpur Highway, Rajasthan 345001',
    latitude: 26.9150,
    longitude: 71.0250,
    googleMapLink: 'https://goo.gl/maps/war-museum-link',
    images: ['', '', '', '', ''],
    videos: [''],
    shortDesc: 'A tribute to the Indian Army\'s bravery in the desert.',
    longDesc: 'Established to showcase the history of the Longewala battle. It features captured tanks, fighter jets, and an audio-visual room.',
    precautionAndSafety: ['Maintain discipline as it is an army-maintained site.'],
    metadata: [
      { label: 'Open Time', data: '9:00 AM' },
      { label: 'Close Time', data: '6:00 PM' },
      { label: 'Entry Fees', data: 'Free Entry (Nominal fee for movie)' },
    ],
    ticketPrice: 0,
    isActive: true,
  },
  {
    name: 'Vintage Car Museum',
    slug: 'vintage-car-museum-udaipur',
    type: 'museum',
    country: 'India',
    state: 'Rajasthan',
    city: 'Udaipur',
    location: 'Gulab Bagh Rd, Udaipur, Rajasthan 313001',
    latitude: 24.5770,
    longitude: 73.6920,
    googleMapLink: 'https://goo.gl/maps/vintage-cars',
    images: ['', '', '', '', ''],
    videos: [''],
    shortDesc: 'The royal collection of classic cars owned by Mewar Maharajas.',
    longDesc: 'Includes the 1934 Rolls-Royce Phantom and several Cadillacs used by the royal family of Udaipur.',
    precautionAndSafety: ['Do not touch the vehicles.'],
    metadata: [
      { label: 'Open Time', data: '9:00 AM' },
      { label: 'Close Time', data: '9:00 PM' },
      { label: 'Entry Fees', data: '₹400 (Approx per person)' },
    ],
    ticketPrice: 40000,
    isActive: true,
  },
  {
    name: 'Anokhi Museum of Hand Printing',
    slug: 'anokhi-museum',
    type: 'museum',
    country: 'India',
    state: 'Rajasthan',
    city: 'Jaipur',
    location: 'Anokhi Haveli, Kheri Gate, Amer, Jaipur, Rajasthan 302028',
    latitude: 26.9880,
    longitude: 75.8500,
    googleMapLink: 'https://goo.gl/maps/anokhi-museum',
    images: ['', '', '', '', ''],
    videos: [''],
    shortDesc: 'Dedicated to the traditional art of woodblock printing.',
    longDesc: 'Located in a restored haveli, this museum preserves the complex craft of hand-block printing through live demonstrations.',
    precautionAndSafety: ['Photography of certain exhibits is restricted.'],
    metadata: [
      { label: 'Open Time', data: '10:30 AM' },
      { label: 'Close Time', data: '4:30 PM' },
      { label: 'Entry Fees', data: '₹30 (Indians), ₹80 (Foreigners)' },
    ],
    ticketPrice: 3000,
    isActive: true,
  },
  {
    name: 'Bagore Ki Haveli Museum',
    slug: 'bagore-ki-haveli',
    type: 'museum',
    country: 'India',
    state: 'Rajasthan',
    city: 'Udaipur',
    location: 'Gangaur Ghat Marg, Udaipur, Rajasthan 313001',
    latitude: 24.5794,
    longitude: 73.6828,
    googleMapLink: 'https://goo.gl/maps/bagore-haveli',
    images: ['', '', '', '', ''],
    videos: [''],
    shortDesc: 'An 18th-century palace showcasing Mewar culture.',
    longDesc: 'Houses the world\'s largest turban and features evening Dharohar folk dance performances.',
    precautionAndSafety: ['Visit in the evening for the dance show.'],
    metadata: [
      { label: 'Open Time', data: '10:00 AM' },
      { label: 'Close Time', data: '7:00 PM' },
      { label: 'Entry Fees', data: '₹60 (Indians), ₹100 (Foreigners)' },
    ],
    ticketPrice: 6000,
    isActive: true,
  },
  {
    name: 'Fateh Prakash Palace Museum',
    slug: 'fateh-prakash-museum-chittorgarh',
    type: 'museum',
    country: 'India',
    state: 'Rajasthan',
    city: 'Chittorgarh',
    location: 'Chittorgarh Fort, Rajasthan 312001',
    latitude: 24.8900,
    longitude: 74.6460,
    googleMapLink: 'https://goo.gl/maps/fateh-prakash',
    images: ['', '', '', '', ''],
    videos: [''],
    shortDesc: 'A palace converted into a museum within Chittorgarh Fort.',
    longDesc: 'Displays a large collection of weapons, shields, and sculptures from the medieval period.',
    precautionAndSafety: ['Check for holiday closures.'],
    metadata: [
      { label: 'Open Time', data: '10:00 AM' },
      { label: 'Close Time', data: '4:30 PM' },
      { label: 'Entry Fees', data: '₹10 (Indians), ₹50 (Foreigners)' },
    ],
    ticketPrice: 1000,
    isActive: true,
  },
  {
    name: 'Ganga Government Museum',
    slug: 'ganga-museum-bikaner',
    type: 'museum',
    country: 'India',
    state: 'Rajasthan',
    city: 'Bikaner',
    location: 'Public Park, Bikaner, Rajasthan 334001',
    latitude: 28.0160,
    longitude: 73.3150,
    googleMapLink: 'https://goo.gl/maps/ganga-museum',
    images: ['', '', '', '', ''],
    videos: [''],
    shortDesc: 'Known for its Harappan artifacts and Silk Road textiles.',
    longDesc: 'Built in 1937, it is one of the best museums in the state for historical research and prehistoric findings.',
    precautionAndSafety: ['Guided tours are recommended for researchers.'],
    metadata: [
      { label: 'Open Time', data: '10:00 AM' },
      { label: 'Close Time', data: '5:00 PM' },
      { label: 'Entry Fees', data: '₹20 (Indians), ₹100 (Foreigners)' },
    ],
    ticketPrice: 2000,
    isActive: true,
  },
];

// ---------------------------------------------------------------------------
// Seed runner
// ---------------------------------------------------------------------------

async function seed() {
  console.log('🌱  Starting database seed...\n');

  let inserted = 0;
  let skipped = 0;

  for (const p of places) {
    try {
      await db
        .insert(place)
        .values(p)
        .onConflictDoNothing({ target: place.slug });

      console.log(`  ✅  ${p.type.padEnd(8)}  ${p.name}  (${p.city}) — ₹${(p.ticketPrice ?? 0) / 100}`);
      inserted++;
    } catch (err) {
      console.warn(`  ⚠️   Skipped "${p.name}" — ${(err as Error).message}`);
      skipped++;
    }
  }

  console.log(`\n🏁  Seed complete — ${inserted} inserted, ${skipped} skipped.\n`);

  await pool.end();
}

seed().catch((err) => {
  console.error('❌  Seed failed:', err);
  pool.end();
  process.exit(1);
});
